name: run main.py

on:
    # https://docs.github.com/fr/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#schedule
    #schedule:
      # https://www.python-engineer.com/posts/run-python-github-actions/#cron-syntax-refresher
      #- cron: '0 14 * * *' # Every day at 14h00 UTC

    # https://docs.github.com/fr/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#push
    push:
        branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: checkout repo content
          # https://github.com/marketplace/actions/checkout
          uses: actions/checkout@v4.2.0

        - name: setup python
          # https://github.com/marketplace/actions/setup-python
          uses: actions/setup-python@v5.2.0
          with:
            python-version: '3.10'

        - name: install python packages
          run: |
            python -m pip install --upgrade pip
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

        - name: execute python script
          run: python main.py
